[package]
name = "jolt"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.2"
yew = { git = "https://github.com/DenisKolodin/yew", rev = "a33a89f0f185a157b4440ad82eef66daf5f98896" }
